targets:
  $default:
    builders:
      entity_generator|entityBuilder:
        generate_for:
          - package:entity_generator/**


builders:
  entityBuilder:
    import: "package:entity_generator/builder.dart"
    builder_factories: ["entityBuilder"]
    build_extensions: {".dart": [".entity_generator.dart"]}
    runs_before:
      - freezed
      - json_serializable
    auto_apply: dependents
    build_to: source


  modelExtensionBuilder:
    import: "package:entity_generator/builder.dart"
    builder_factories: ["modelExtensionBuilder"]
    build_extensions: {".dart": [".entity_extension.dart"]}
    auto_apply: dependents
    build_to: source